name: CI

on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
 
  build:
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      - uses: actions/checkout@v3

     
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: flake8 Lint
        run: pip install -r requerements.txt
      
      # Runs a set of commands using the runners shell
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .   