name: Code checks

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v1
    - name: Install python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.4
    - name: Install deps
    run: |
        python -m pip install --upgrade pip
        pip install -r requerements.txt
    - name: Run flake8
    run: flake8 .
    - name: Run mypy
    run: mypy .           
